### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by SViccari** [bostonrb/bostonrb.org#55]
Now, this is a story all about how
bostonrb got flipped-turned upside down
And I'd like to take a minute
Just sit right there
I'll tell you how we need to fix our site via Cloudflare

----
@mxie - Hi! Looking into why the site is down, I saw in the audit logs for Cloudflare that your account ran a purge action on January 1, 2020. Do you know any details about this? Did you perhaps delete your Cloudflare account? It seems to have removed the bostonrb site from Cloudflare, which I believe is why the site is currently down.

Thanks!

**Comment by pcai** [comment]
hello from the future - I believe this is fixed https://www.bostonrubygroup.com/
